"""empty message

Revision ID: 8d17cd289c05
Revises: 
Create Date: 2022-09-23 10:48:23.259064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d17cd289c05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical__history',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('user_seq', sa.Integer(), nullable=False),
    sa.Column('medical_cd', sa.String(length=25), nullable=True),
    sa.Column('medical_nm', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('re_dt', sa.String(length=500), nullable=True),
    sa.Column('md_dt', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('seq', 'user_seq')
    )
    op.create_table('medical__info',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('medical_cd', sa.String(length=25), nullable=True),
    sa.Column('medical_nm', sa.String(length=255), nullable=True),
    sa.Column('re_dt', sa.String(length=500), nullable=True),
    sa.Column('md_dt', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('medicine__color',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=25), nullable=True),
    sa.Column('re_dt', sa.String(length=500), nullable=True),
    sa.Column('md_dt', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('medicine__division',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=25), nullable=True),
    sa.Column('re_dt', sa.String(length=500), nullable=True),
    sa.Column('md_dt', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('medicine__history',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('user_seq', sa.Integer(), nullable=False),
    sa.Column('medicine_cd', sa.String(length=25), nullable=True),
    sa.Column('medicine_nm', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('re_dt', sa.String(length=500), nullable=True),
    sa.Column('md_dt', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('seq', 'user_seq')
    )
    op.create_table('medicine__info',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('medicine_cd', sa.String(length=25), nullable=True),
    sa.Column('medicine_nm', sa.String(length=255), nullable=True),
    sa.Column('shape_seq', sa.Integer(), nullable=True),
    sa.Column('color_seq', sa.Integer(), nullable=True),
    sa.Column('division_seq', sa.Integer(), nullable=True),
    sa.Column('re_dt', sa.String(length=500), nullable=True),
    sa.Column('md_dt', sa.String(length=500), nullable=True),
    sa.Column('entp_cd', sa.String(length=50), nullable=True),
    sa.Column('entp_nm', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('medicine__shape',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('shape', sa.String(length=25), nullable=True),
    sa.Column('re_dt', sa.String(length=500), nullable=True),
    sa.Column('md_dt', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('re_dt', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('user')
    op.drop_table('question')
    op.drop_table('medicine__shape')
    op.drop_table('medicine__info')
    op.drop_table('medicine__history')
    op.drop_table('medicine__division')
    op.drop_table('medicine__color')
    op.drop_table('medical__info')
    op.drop_table('medical__history')
    # ### end Alembic commands ###
